name: wallet_connect_cardano
description: WalletConnect v2 communication bridge for Cardano wallets implementing CIP-30.
version: 0.0.1
homepage: https://github.com/vespr-wallet/wallet_connect_cardano

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  reown_walletkit: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
